### ISSUE TITLE
Upgrade to latest version of confluence-publisher

### ISSUE THREAD

**Issue by dzeigler** [nomisp/confluence-publisher-plugin#10]
Please consider upgrading the confluence publisher dependency to the latest available version. Currently, 0.17.1 is available with several improvements and fixes from the version available in the 0.2.0 release of this project.

**Comment by alexeygolikov** [comment]
+1

**Comment by nomisp** [comment]
It's already planned. Once I find the time, I'll do the upgrade and create a new version of the plugin. Hopefully within the next days.

**Comment by nomisp** [comment]
Version 0.3.0 of the plugin, using version 0.17.1 of confluence-publisher is released.
