### ISSUE TITLE
Allow external Doc Properties

### ISSUE THREAD

**Issue by goshe** [nomisp/confluence-publisher-plugin#12]
Hello Markus,

is there a specific reason, why the document attributes are set to internal ?
https://github.com/nomisp/confluence-publisher-plugin/blob/e3a0c7198ba6ea1e820cd501b22c5517a9330f03/src/main/groovy/ch/nomisp/confluence/publisher/PublishToConfluenceTask.groovy#L86

The missing parameter is the only thing which is missing to use this plugin in a project. 

Cheers, 
Rene

**Comment by dzeigler** [comment]
Hi Rene,
I think this is a gap in the project documentation. I recently wondered the
same thing but found I was able to set attributes as follows in my
build.gradle.

```
confluencePublisher {
  spaceKey = 'example'
  ...
  attributes = [
    'bpmn-js': 'path/to/bpmn-js',
    'dot': 'path/to/dot'
  ]
}
```

Those attributes get passed through as expected to asciidoctor, and the
custom paths are used by asciidoctor-diagram during the publish to
confluence task of my build.


Hope that helps,
David

**Comment by goshe** [comment]
Hello David, 

yes that helps indeed will try and report :-)

Cheers,
Rene

**Comment by goshe** [comment]
Hello David, 

thanks for your quick reply. 
It works :-)

Now I just need to identify how I can use the OrphanRemovalStrategy in my gradle. 
Sadly the Plugin does not support just using a String :-/ 

Do you maybe have an Idea ?

Cheers,
Rene

**Comment by nomisp** [comment]
> 

Hi Rene
Thanks for the hint concerning the lack in the documentation of the attributes. I'll add it to the user documentation.

To use the OrphanRemovalStrategy you can just import org.sahli.asciidoc.confluence.publisher.client.OrphanRemovalStrategy in your build.gradle and then use this enum in the plugin configuration e.g. orphanRemovalStrategy = OrphanRemovalStrategy.KEEP_ORPHANS
It's described in the user documentation: [User documentation](https://nomisp.github.io/confluence-publisher-plugin/index/user-guide.html#_configuration_of_the_publishtoconfluence_task)

Greetings
Peter
