### ISSUE TITLE
Expose convertOnly

### ISSUE THREAD

**Issue by BartDubois** [nomisp/confluence-publisher-plugin#17]
I would like to use `convertOnly` property of publisher to validate the documentation without publishing.
This will be used on feature branches and in merge requests.

The property is exposed in task code but adding it in the build script on task cause an error.

```
Unresolved reference: convertOnly
```

**Comment by nomisp** [comment]
Hi @BartDubois 
How did you use convertOnly?

It is a commandline parameter and can be uses like this:
`./gradlew publishToConfluence --convertOnly`

[See also the userguide](https://nomisp.github.io/confluence-publisher-plugin/index/user-guide.html)

Regards
Peter

**Comment by BartDubois** [comment]
I try it by adding it as property of the task. Have it as parameter is great and should work form my case. Thanks!

**Comment by BartDubois** [comment]
`--convertOnly` works.
