### ISSUE TITLE
Proxy requres user name and password

### ISSUE THREAD

**Issue by BartDubois** [nomisp/confluence-publisher-plugin#19]
https://github.com/nomisp/confluence-publisher-plugin/blob/eb2935396198e1e4b5d668e3278d99da5bc9a972/src/main/groovy/ch/nomisp/confluence/publisher/PublishToConfluenceTask.groovy#L184-L190

From the code it looks like using proxy requres the user name and password. Some proxies are open and do not need those.

**Comment by nomisp** [comment]
Hi @BartDubois
Thanks for the hint.
I'll fix that and create a new version.

Regards
Peter
