### ISSUE TITLE
Java 8 support

### ISSUE THREAD

**Issue by dzeigler** [nomisp/confluence-publisher-plugin#2]
Hi,
I'm working on a project that's still on Java 8. Could you consider building a new version of the plugin with something like this in your build.gradle?

```
java {
  sourceCompatibility = JavaVersion.VERSION_1_8
  targetCompatibility = JavaVersion.VERSION_1_8
}
```
Thanks!

**Comment by nomisp** [comment]
Hi @dzeigler 
Thanks for your request.

I just released version 0.2.0 of the plugin.
This new version now supports projects using Java8.
In addition the ancestorId is now defined as String to better support Confluence cloud.

I hope you can use the plugin now and it fullfills your needs.

Regards
Peter
