### ISSUE TITLE
would be great to register additional publish tasks dynamically

### ISSUE THREAD

**Issue by encodeering** [nomisp/confluence-publisher-plugin#5]
hey, how is it going?

we have a project with directories, each hosting an individual ascii doc and were wondering if it would make sense to

1. make the task registration optional/configurable as it may not be needed in this case
2. move the constant name of the task into the signature of the task factory, so that we can simply call the function from gradle to dynamically generate additional publish tasks , e.g. with a suffix name of the corresponding sub directory. we could then create a regular publishToConfluence task delegating to those newly created tasks.

https://github.com/nomisp/confluence-publisher-plugin/blob/3c9a3c591af82138ec047d6fe4055c797430a3d2/src/main/groovy/ch/nomisp/confluence/publisher/ConfluencePublisherPlugin.groovy#L29-L33

do you think that could work in the current implementation?

cheers!

**Comment by nomisp** [comment]
Hi @encodeering 
Doesn't something like:
`tasks.register('mySecondPublishToConfluenceTask', PublishToConfluenceTask) {
...
}`
or
`task myThirdPublishToConfluenceTask(type: PublishToConfluenceTask) {
...
}`
in your build.gradle work for you?

Or have I missunderstood your problem?

Cheers
Peter

**Comment by encodeering** [comment]
hey @nomisp 

yes, that's what we tried, using the following lines:

```
files(projectDir).asFileTree.filter { it.name == "index.adoc" }.forEach {
    val source = it.parentFile

    tasks.register("publishToConfluence${source.name}", PublishToConfluenceTask::class) {
        group = "publishing"
    }
}
```

but these tasks, in contrast to the one that the plugin configures, don't seem to inherit the properties from the extension. the current error message is that the `asciiDocRootFolder` is not configured. however, this one should most likely not be set by the extension in this use-case, but might give some context.

it would indeed be great to just generate new tasks as you described, without knowing the plugin's factory. that would be a better solution.

oops, forgot to mention the version, which is `"0.2.0"`. hope this explains it better or do you have another idea how to accomplish this?

cheers

**Comment by nomisp** [comment]
Hi @encodeering 
The `asciiDocRootFolder` you need to specify for each of your individual AsciiDoc documentation folder as it's always a different one (maybe also others like the ancestorId). In you case `asciiDocRootFolder` would be just `source`.
The other mandatory fields could be reused from the publishToConfluence task configuration (extension) e.g. `rootConfluenceUrl = confluencePublisher.rootConfluenceUrl`.

So in your case it could look like the following:
```
files(projectDir).asFileTree.filter { it.name == "index.adoc" }.forEach {
    File source = it.parentFile

    tasks.register("publishToConfluence${source.name}", PublishToConfluenceTask) {
        group = "publishing"
        asciiDocRootFolder = source
        rootConfluenceUrl = confluencePublisher.rootConfluenceUrl
        spaceKey = confluencePublisher.spaceKey
        ancestorId = confluencePublisher.ancestorId
        username = confluencePublisher.username
        password = confluencePublisher.password
    }
}
```

Cheers
Peter

**Comment by encodeering** [comment]
Hi @nomisp,

yes indeed, copying them over would work, just thought it might be helpful if the plugin copies them implicitly, like spacekey, username, .. and so forth, anything that would likely stay constant. that would make plugin updates more convenient, without checking what other defaults from extension could be valuable.

it would also be great to disable the auto-registered task, as it wouldn't be required in this particular case.

thanks for the feedback and suggestions, appreciated!

cheers
